from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class JobStatus(str, Enum):
    QUEUED = "QUEUED"
    IN_PROGRESS = "IN_PROGRESS"
    NEEDS_CONTEXT = "NEEDS_CONTEXT"
    HITL = "HITL"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class ChatMessage(BaseModel):
    role: str
    content: str


class Fact(BaseModel):
    key: str
    value: str
    source: str


class Asset(BaseModel):
    type: str
    data: str  # base64-encoded


class Job(BaseModel):
    job_id: str
    session_id: str
    status: JobStatus
    active_agent: str = ""
    hop_count: int = 0
    prompt: str = ""
    collected_facts: list[Fact] = Field(default_factory=list)
    generated_assets: list[Asset] = Field(default_factory=list)
    missing_queries: list[str] = Field(default_factory=list)
    final_result: str = ""


class Session(BaseModel):
    session_id: str
    chat_history: list[ChatMessage] = Field(default_factory=list)


class TaskPayload(BaseModel):
    job_id: str
    session_id: str


# --- LLM structured output schemas ---


class ResearchFacts(BaseModel):
    """Structured facts extracted by the researcher."""

    facts: list[Fact]


class AnalysisCode(BaseModel):
    """Python code generated by the analyst."""

    code: str
    explanation: str


class FinalAnswer(BaseModel):
    """Aggregated final answer."""

    summary: str
    key_findings: list[str]
